name: PR Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run npm install
      run: npm install

    - name: Set PR status
      if: success()
      run: gh pr check --success --body "Build succeeded"
